Dev
trueanqu/sample_shop pull request #2
Opened 2016-10-03 06:29 UTC by trueanqu

Добавлен роутер (Router). Некоторые изменения претерпел класс Request: хардкодные набор поддерживаемых методов http-запроса и шаблон для фильтрации входящих URI вынесены в конфигурационный файл config/request.php

2016-10-06 19:00 UTC, ddavidov approved these changes

2016-10-06 19:00 UTC, ddavidov commented on config/routes.php
>          'method' => 'getOrders'
Тут вроде норм, то, что нужно.

2016-10-06 19:00 UTC, ddavidov commented on vendor/trueanqu/Framework/App.php
> +        $router = Router::getInstance();
Маловато будет...

2016-10-06 19:00 UTC, ddavidov commented on vendor/trueanqu/Framework/Request.php
>      public function filterUri()
Не очень понятен смысл этого

2016-10-06 19:00 UTC, ddavidov commented on vendor/trueanqu/Framework/Router.php
> +    }
Добавь 
```
parseRoute($route_name, $params = []);
```

2016-10-07 06:12 UTC, trueanqu commented on vendor/trueanqu/Framework/Request.php
>      public function filterUri()
@ddavidov  Да, я понял. Это я пытался вид запроса ограничить. И еще параметры фильтровать гета, но это вообще не так делать нужно, я немного начудил)

2016-10-09 07:42 UTC, Artiomtb requested changes

2016-10-09 07:42 UTC, Artiomtb commented on vendor/trueanqu/Framework/Router.php
> +        foreach($routes as $key => $value)
$routes[$name] ???

2016-10-12 08:37 UTC, merged